
export const metadata = {
  title: 'Profile || Next App',
  description: 'Generated by create next app',
}


const ProfilePage = ()=>{
  return(
    <div>
      ProfilePage
    </div>
  )
}
export default ProfilePage;