import React from 'react';

export const metadata = {
  title: 'Dashboard Next App',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      dash board
    </div>
  );
};

export default page;